#ifndef IRCNUMERIC_HPP
#define IRCNUMERIC_HPP

enum ErrorCode {
	// Replies (RPL)
    RPL_WELCOME = 1,   // "001"
    RPL_YOURHOST = 2,  // "002"
    RPL_CREATED = 3,   // "003"
    RPL_MYINFO = 4,    // "004"

    // Errors (ERR)
    ERR_UNKNOWNCOMMAND = 421,

    ERR_NONICKNAMEGIVEN = 431,
    ERR_ERRONEUSNICKNAME = 432,
    ERR_NICKNAMEINUSE = 433,

    ERR_NOSUCHNICK = 401,
    ERR_NORECIPIENT = 411,
    ERR_NOTEXTTOSEND = 412,

    ERR_NOTREGISTERED = 451,
    ERR_NEEDMOREPARAMS = 461,
    ERR_ALREADYREGISTRED = 462,
    ERR_PASSWDMISMATCH = 464
};


#endif