#ifndef IRCNUMERIC_HPP
#define IRCNUMERIC_HPP

enum IrcNumeric {
    // Replies (RPL)
    RPL_WELCOME = 1,      // 001
    RPL_YOURHOST = 2,     // 002
    RPL_CREATED = 3,      // 003
    RPL_MYINFO = 4,       // 004

    RPL_CHANNELMODEIS = 324,
    RPL_NOTOPIC = 331,
    RPL_TOPIC = 332,
    RPL_INVITING = 341,
    RPL_NAMREPLY = 353,
    RPL_ENDOFNAMES = 366,

    // Errors (ERR)
    ERR_NOSUCHNICK = 401,
    ERR_NOSUCHCHANNEL = 403,
    ERR_CANNOTSENDTOCHAN = 404,

    ERR_UNKNOWNCOMMAND = 421,

    ERR_NONICKNAMEGIVEN = 431,
    ERR_ERRONEUSNICKNAME = 432,
    ERR_NICKNAMEINUSE = 433,

    ERR_USERNOTINCHANNEL = 441,
    ERR_NOTONCHANNEL = 442,

    ERR_NORECIPIENT = 411,
    ERR_NOTEXTTOSEND = 412,

    ERR_CHANNELISFULL = 471,
    ERR_INVITEONLYCHAN = 473,
    ERR_BADCHANNELKEY = 475,

    ERR_CHANOPRIVSNEEDED = 482,

    ERR_NOTREGISTERED = 451,
    ERR_NEEDMOREPARAMS = 461,
    ERR_ALREADYREGISTRED = 462,
    ERR_PASSWDMISMATCH = 464
};

#endif
