#ifndef IRCNUMERIC_HPP
#define IRCNUMERIC_HPP

enum ErrorCode {
    ERR_UNKNOWNCOMMAND = 421,
    ERR_NONICKNAMEGIVEN = 431,
    ERR_ERRONEUSNICKNAME = 432,
    ERR_NICKNAMEINUSE = 433,
    RPL_WELCOME = 001
};


#endif